
proxy:
  port: 8080
  authentication: none
  template-path: ./templates
  docker:
      internal-networking: true
  specs:
  - id: shiny-report-front
    display-name: Chronik-Report
    description: Erstelle einen Datenbericht zu rechter Gewalt
    container-cmd: ["R", "-e", "golem::document_and_reload(); options('shiny.port'=3838,shiny.host='0.0.0.0'); rightwatching::run_app()"]
    container-volumes: ["/root/rechtsaussen-shiny-app/data/:/build_zone/data/"]
    container-image: chris1oph/rightwatching
    container-network: sp-net
  support:
    mail-to-address: christoph@rightwatching.org
    mail-from-address: support@rightwatching.org
  container-log-path: /opt/shinyproxy/logs/

spring:
  mail:
    host: desdemonia.uberspace.de
    # TLS: 587 SSL: 465 Plain: 25
    port: 587
    username: support@rightwatching.org
    password: my_password
    properties:
      # For StartTLS
      mail.smtp.starttls.enable: true
      # For SSL
      #mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory

logging:
  file:
    /opt/shinyproxy/logs/shinyproxy.log